DigiChamps/Models/Orderdetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DigiChamps.Models
{
    public class Orderdetails
    {
        public class orders
        {
          //  public Nullable<int> OrderPkg_ID { get; set; }
            //public Nullable<int> Package_ID { get; set; }
            //public string Package_Name { get; set; }
            //public string Package_Desc { get; set; }
            //public Nullable<System.DateTime> Expiry_Date { get; set; }
            //public string Board_Name { get; set; }
            //public string Class_Name { get; set; }
            //public string Chapters { get; set; }
            //public string Regd_No { get; set; }
            //public string subjects { get; set; }
            //public string Customer_Name { get; set; }
            //public string Email { get; set; }
            //public string Mobile { get; set; }
            //public string Phone { get; set; }
            //public string Pincode { get; set; }
            //public string Address { get; set; }

            public int Order_ID { get; set; }
            public Nullable<System.DateTime> order_date { get; set; }
          
            public string Order_No { get; set; }
            public Nullable<int> Regd_ID { get; set; }
            public Nullable<decimal> tax_Amt { get; set; }
            public Nullable<decimal> Total { get; set; }
            public int Count { get; set; }

            public string Discount { get; set; }

            public decimal? Grand_Total { get; set; }
        }
        public class success
        {
            public List<orders> order { get; set; }

        }
        public class getorders
        {
            public success success { get; set; }
        }

        public class Errorresult
        {
            public Errorresponse Error { get; set; }
        }
        public class Errorresponse
        {
            public string Message { get; set; }
        }


    }
}

DigiChamps/Models/PackagePreviewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.Entity;
using DigiChamps.Models;
using System.Security.Authentication;
using System.Security.Cryptography;
using System.Web.Security;
using System.Text;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace DigiChamps.Models
{
    public class PackagePreviewModel
    {
        public string USER_CODE { get; set; }
        public string USER_NAME { get; set; }

        public int Regd_ID { get; set; }
        public string Regd_No { get; set; }
        public string Customer_Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }

        public int RegdDtl_ID { get; set; }
        public string Year { get; set; }

        public int PackageDtl_ID { get; set; }
        public Nullable<int> Package_ID { get; set; }
        public Nullable<int> Board_Id { get; set; }
        public string Board_Name { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public string Class_Name { get; set; }
        public Nullable<int> Subject_Id { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Chapter_Id { get; set; }
        public string Chapter { get; set; }

        public string Package_Name { get; set; }
        public string Package_Desc { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Total_Chapter { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<int> Subscripttion_Period { get; set; }
        
        public int PackageSubDtl_ID { get; set; }
        public Nullable<int> SubScription_Limit { get; set; }

        public int Module_ID { get; set; }
        public string Module_Name { get; set; }
        public string Module_Desc { get; set; }
        public string Module_Content { get; set; }
        public string Module_video { get; set; }
        public DateTime? Inserted_Date { get; set; }
        public Nullable<bool> Is_Offline { get; set; }

        public int? Tablet_Id { get; set; }

        public int DIYVideo_ID { get; set; }
        public string DIYVideo_Name { get; set; }
        public string DIYVideo_Upload { get; set; }
        public string DIYVideo_Description { get; set; }
    }
}

DigiChamps/Controllers/FAQController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using DigiChamps.Models;

namespace DigiChamps.Controllers
{
    public class FAQController : ApiController
    {
        DigiChampsEntities db = new DigiChampsEntities();
        DateTime today = DigiChampsModel.datetoserver();

        public class ErrorResult
        {
            public ErrorResponse Error { get; set; }
        }

        public class ErrorResponse
        {
            public string Message { get; set; }
        }

        public class SuccessResponse
        {
            public string Message { get; set; }
        }
        public class SuccessResult
        {

            public List<FAQ> Faqs { get; set; }
        }


        public class FAQ
        {
            public int? FAQ_Id { get; set; }
            public string Answer { get; set; }
            public string Question { get; set; }



        }

        public class FAQ_List
        {
            public List<FAQ> list { get; set; }
        }
        public class success_FAQ
        {
            public FAQ_List Success { get; set; }
        }
        public class Errorresult
        {
            public Errorresponse Error { get; set; }
        }
        public class Errorresponse
        {
            public string Message { get; set; }
        }
        [HttpGet]
        public HttpResponseMessage GetFAQ()
        {
            try
            {
                var obj = new success_FAQ
                {
                    Success = new FAQ_List
                    {
                        list = (from c in db.tbl_DC_FAQs.Where(x => x.Is_Active == true && x.Is_Deleted == false)
                                select new FAQ
                                {

                                    FAQ_Id = c.FAQs_ID,
                                    Answer = c.FAQ_Answer,
                                    Question = c.FAQ
                                }).ToList(),

                    }
                };

                return Request.CreateResponse(HttpStatusCode.OK, obj);
            }
            catch (Exception)
            {

                var obj = new Errorresult
                {
                    Error = new Errorresponse
                    {
                        Message = "Something went wrong."
                    }
                };
                return Request.CreateResponse(HttpStatusCode.OK, obj);
            }
        }
    }
}

DigiChamps/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using DigiChamps.Models;
using DigiChamps.Controllers;
using System.Web.Security;
using System.IO;
using System.Text;
using System.Net;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Drawing.Imaging;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Collections.Specialized;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using CCA.Util;
using System.Globalization;
using ClosedXML.Excel;

namespace DigiChamps.Controllers
{
    [HandleError]
    public class StudentController : Controller
    {
        DigiChampsEntities DbContext = new DigiChampsEntities();
        DateTime today = DigiChampsModel.datetoserver();

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Board_Id = new SelectList(DbContext.tbl_DC_Board.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Board_Id", "Board_Name");
            ViewBag.secureqsn = new SelectList(DbContext.tbl_DC_Security_Question.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Security_Question_ID", "Security_Question");
            ViewBag.blog = DbContext.tbl_DC_Marketing_Blog.Where(x => x.Is_Active == true && x.Is_Deleted == false).ToList();
            ViewBag.team = DbContext.tbl_DC_Our_Team.Where(x => x.Is_Active == true && x.Is_Deleted == false).ToList();

            if (Session["USER_CODE"] != null)
            {
                if (Session["ROLE_CODE"].ToString() == "C")
                {
                    return RedirectToAction("studentdashboard", "student");
                }
                else
                {
                    return RedirectToAction("logout");
                }
            }
            return View();
        }
        [HttpPost]
        public JsonResult Index(string User_name, string password)
        {
            string msg = string.Empty;
            try
            {
                string pass_word = DigiChampsModel.Encrypt_Password.HashPassword(password);
                var obj = DbContext.tbl_DC_USER_SECURITY.Where(x => x.USER_NAME == User_name).FirstOrDefault();

                if (obj != null)
                {
                    if (obj.PASSWORD == pass_word)
                    {
                        if (obj.STATUS == "A")
                        {
                            if (obj.ROLE_CODE == "C")
                            {
                                if (obj.IS_ACCEPTED == true)
                                {
                                    Session["USER_CODE"] = obj.USER_CODE;
                                    Session["USER_NAME"] = obj.USER_NAME;
                                    Session["ROLE_CODE"] = obj.ROLE_CODE;
                                    TempData["USER_NAME"] = obj.USER_NAME;
                                    Session["Time"] = today.ToShortTimeString();
                                    ///  FormsAuthentication.RedirectFromLoginPage(obj.USER_NAME, false);
                                    string mm = Session["USER_CODE"].ToString();
                                    var _student_details = DbContext.tbl_DC_Registration.Where(x => x.Mobile == mm).FirstOrDefault();
                                    int sreg_id = Convert.ToInt32(_student_details.Regd_ID);
                                    Session["std_name"] = _student_details.Customer_Name;
                                    if (_student_details.Image == null || _student_details.Image == "")
                                    {
                                        Session["student_profile"] = "/Student_assets/assets/images/avatar/one.png";
                                    }
                                    else
                                    {
                                        Session["student_profile"] = "/images/Profile/" + _student_details.Image;
                                    }

                                    var chkbrd_cls = DbContext.tbl_DC_Registration_Dtl.Where(x => x.Regd_ID == sreg_id && x.Is_Active == true && x.Is_Deleted == false).FirstOrDefault();
                                    if (chkbrd_cls == null)
                                    {
                                        msg = "0"; //choose board
                                    }
                                    else
                                    {
                                        Session["class"] = chkbrd_cls.Class_ID;
                                        msg = "1"; //board already there
                                    }
                                }
                                else
                                {
                                    msg = "-5";
                                }
                            }
                            else
                            {
                                msg = "Please login as a student.";
                            }
                        }
                        else
                        {
                            msg = "-1"; //otp conformation
                        }
                    }
                    else
                    {
                        msg = "-3"; // "Password doesnot match.";
                    }
                }
                else
                {
                    msg = "-4";   // "User name is not yet registered.";
                }
            }
            catch (Exception ex)
            {
                ex.Message.ToString();
                msg = "-2";
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult letsbegin(string mobno)
        {
            string msg = string.Empty;
            string msg1 = string.Empty;
            try
            {
                if (mobno != null)
                {
                    var data = DbContext.tbl_DC_Registration.Where(x => x.Mobile == mobno && x.Is_Active == true && x.Is_Deleted == false).FirstOrDefault();
                    if (data != null)
                    {
                        msg = "1"; //Number registered and redirect to login page
                        ViewBag.number = data.Mobile;
                    }
                    else
                    {
                        msg = "2"; //Number not registered and redirect to sign up page

                        ViewBag.number = mobno;
                    }
                }
            }
            catch (Exception ex)
            {
                msg = "0"; // Something went wrong
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult PrivacyPolicy()
        {
            ViewBag.Board_Id = new SelectList(DbContext.tbl_DC_Board.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Board_Id", "Board_Name");
            ViewBag.secureqsn = new SelectList(DbContext.tbl_DC_Security_Question.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Security_Question_ID", "Security_Question");

            return View();
        }


        [HttpGet]
        public ActionResult Pricing()
        {
            ViewBag.Board_Id = new SelectList(DbContext.tbl_DC_Board.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Board_Id", "Board_Name");
            ViewBag.secureqsn = new SelectList(DbContext.tbl_DC_Security_Question.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Security_Question_ID", "Security_Question");

            return View();
        }

        [HttpGet]
        public ActionResult TermsAndConditions()
        {
            ViewBag.Board_Id = new SelectList(DbContext.tbl_DC_Board.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Board_Id", "Board_Name");
            ViewBag.secureqsn = new SelectList(DbContext.tbl_DC_Security_Question.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Security_Question_ID", "Security_Question");


            return View();
        }
        [HttpGet]
        public ActionResult RefundsAndCancellation()
        {
            ViewBag.Board_Id = new SelectList(DbContext.tbl_DC_Board.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Board_Id", "Board_Name");
            ViewBag.secureqsn = new SelectList(DbContext.tbl_DC_Security_Question.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Security_Question_ID", "Security_Question");


            return View();
        }
        [HttpGet]
        public ActionResult contact()
        {
            ViewBag.Board_Id = new SelectList(DbContext.tbl_DC_Board.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Board_Id", "Board_Name");
            ViewBag.secureqsn = new SelectList(DbContext.tbl_DC_Security_Question.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Security_Question_ID", "Security_Question");
            ViewBag.captcha = Createcaptcha(4);
            return View();
        }

        [HttpPost]
        public JsonResult contact(string fname, string lname, string email, string subject, string message, string captcha, string captcha_code)
        {
            string msg = string.Empty;
            try
            {
                if (captcha == captcha_code)
                {
                    StringBuilder sb = new StringBuilder();
                    sb.Append("<body style='margin: 0; padding: 0; border: none;'>");
                    sb.Append("<div style='width: 650px; float: left; border: 5px solid #CCC;color:rgba(255, 255, 255, 0.84); font-family: Arial, Helvetica, sans-serif; font-size: 13px; line-height: 22px; padding: 0; background-color: #36a8f5;'>");
                    sb.Append("<div style='width: 100%; float: left; background-color: #fff; padding: 10px 0px;'>");

DigiChamps/Views/Student/RemarkQuestionBank.cshtml
@{
    ViewBag.Title = "RemarkQuestionBank";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

@{
    ViewBag.Title = "Remarkworksheet";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}
@model List<DigiChamps.Controllers.StudentController.QuestionbankReviewClass>
<style>
    .comment {
        overflow: hidden;
        padding: 0 0 1em;
        border-bottom: 1px solid #ddd;
        margin: 0 0 1em;
        *zoom: 1;
    }

    .comment-img {
        float: left;
        margin-right: 33px;
        border-radius: 5px;
        overflow: hidden;
    }

        .comment-img img {
            display: block;
        }

    .comment-body {
        overflow: hidden;
    }

    .comment .text {
        padding: 10px;
        border: 1px solid #e5e5e5;
        border-radius: 5px;
        background: #fff;
    }

        .comment .text p:last-child {
            margin: 0;
        }

    .comment .attribution {
        margin: 0.5em 0 0;
        font-size: 14px;
        color: #666;
    }

    /* Decoration */

    .comments,
    .comment {
        position: relative;
    }

        .comments:before,
        .comment:before,
        .comment .text:before {
            content: "";
            position: absolute;
            top: 0;
            left: 65px;
        }

        .comments:before {
            width: 3px;
            top: -20px;
            bottom: -20px;
            background: rgba(0,0,0,0.1);
        }

        .comment:before {
            width: 9px;
            height: 9px;
            border: 3px solid #fff;
            border-radius: 100px;
            margin: 16px 0 0 -6px;
            box-shadow: 0 1px 1px rgba(0,0,0,0.2), inset 0 1px 1px rgba(0,0,0,0.1);
            background: #ccc;
        }

        .comment:hover:before {
            background: orange;
        }

        .comment .text:before {
            top: 18px;
            left: 78px;
            width: 9px;
            height: 9px;
            border-width: 0 0 1px 1px;
            border-style: solid;
            border-color: #e5e5e5;
            background: #fff;
            -webkit-transform: rotate(45deg);
            -moz-transform: rotate(45deg);
            -ms-transform: rotate(45deg);
            -o-transform: rotate(45deg);
        }

    .closecomment {
        position: absolute;
        top: 1px;
        right: 6px;
        border-radius: 50%;
        background-color: transparent;
        border: none;
        font-weight: bolder;
        font-size: 0.81rem;
    }
</style>
<div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 nopad-right">
        <div class="row">

            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 questions-cont">
                <div class="panel panel-ntspl">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            Question Bank Remark
                        </h3>

                    </div>
                    <div class="panel-body">
                        <section class="comments">
                            @if (Model.Count() > 0)
                            {
                                foreach (var a in Model)
                                {
                                    <article class="comment">
                                        <a class="comment-img" href="#non">
                                            <img src="~/Student_assets/assets/images/avatar/five.png" alt="@a.Posted_By" width="50" height="50">
                                        </a>
                                        <div class="comment-body">
                                            <div class="text">
                                                <p>@a.Message</p>
                                                @if (a.Attachment != null)
                                                {
                                                    <audio controls>
                                                        <source src="@Url.Content(a.Attachment)" type="audio/ogg">
                                                    </audio>
                                                }
                                            </div>
                                            <p class="attribution">by <a href="#non">@a.Posted_By</a> at @a.Inserted_On.ToString("dd MMM yyyy")</p>
                                        </div>
                                        @if (Session["USER_CODE"] != null)
                                        {
                                            DigiChamps.Models.DigiChampsEntities DbContext = new DigiChamps.Models.DigiChampsEntities();
                                            string mm = Session["USER_CODE"].ToString();
                                            var _student_details = DbContext.tbl_DC_Registration.Where(x => x.Mobile == mm).FirstOrDefault();
                                            int sid = Convert.ToInt32(_student_details.Regd_ID);
                                            if (sid == a.Posted_By_ID)
                                            {
                                                <a class="closecomment" href="/Student/DeleteQuestionBankReview?id=@a.QuestionbankReview_ID&Questionbankid=@a.Questionbank_ID" title="Delete"><i class="fa fa-times"></i></a>
                                            }
                                        }
                                    </article>
                                }
                            }

                            @using (Html.BeginForm("UploadQuestionBankReview", "Student", FormMethod.Post, new { data_ajax = "false", enctype = "multipart/form-data", id = "validation-form1" }))
                            {
                                <article>
                                    <input type="hidden" value="@ViewBag.Questionbank_ID" name="Questionbank_ID" />
                                    <a class="comment-img" href="#non">
                                        <img src="@Session["student_profile"].ToString()" alt="odm" width="50" height="50">
                                    </a>
                                    <div class="comment-body">
                                        <div class="text">
                                            <textarea class="form-control" name="txtcomment" placeholder="Write Remark Here..."></textarea>
                                            <input type="file" accept="audio/*" capture name="audiofile">
                                        </div>
                                        <div class="text-right">
                                            <input type="submit" value="Submit" class="btn btn-primary float-right mt-3" />
                                        </div>
                                    </div>
                                </article>
                            }

                        </section>
                    </div>
                </div>
            </div>


        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                <div class="panel panel-ntspl">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            What's Inside
                        </h3>
                    </div>
                    <div class="panel-body">
                        <div class="inside-box">
                            <span class="video-neww"></span>
                            <div class="right-p">
                                <h3>Lectures Video</h3>
                                <p>Best lectures are guide you to study.</p>
                            </div>
                        </div>
                        <div class="inside-box inside-box-margin">
                            <span class="study-neww"></span>
                            <div class="right-p">
                                <h3>Study Material</h3>
                                <p>Best study material will be provided by our lectures. </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("audio").on("play", function () {
            $("audio").not(this).each(function (index, audio) {
                audio.pause();
            });

        });
    })
</script>

DigiChamps/Views/Student/orderdetails.cshtml
@model IEnumerable<DigiChamps.Models.SP_DC_Order_Details_Result>
@{
    ViewBag.Title = "Order Details | DIGICHAMPS | Learners Beyond Classrooms";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}
<!-- Page Header -->
@section header{
    <i class="menu-icons order-detail-icon doubt-icon page_header_icon"></i>
    <span class="main-text">Order Details</span>
}
<!-- /pageheader -->

<div class="row">
    <div class="col-md-12 questions-cont">
        <!-- Question Panel Starts -->
        <div class="panel panel-ntspl">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Your Order Details
                </h3>
            </div>
            <div class="panel-body">
                @if (Model.Count() != 0)
                {

                    int i = 0; int j = 0;
                    foreach (var item in Model)
                        
                    {
                        
                         if(i % 4 == 0)
    {
        j = 1;               
        @*<div class='table-cont bd-clr-1'>*@

           }

         

           if (i % 4 == 1)
           {
               j = 2;
           }
            @*<div class='table-cont bd-clr-2'>*@

               
                if(i % 4 == 2)
                {
                    j = 3;
                }          
                    @*<div class='table-cont bd-clr-3'>*@


                if (i % 4 == 3)
                {
                    j = 4;
                }
                         <div class="bd-clr-@j">
                        <div class="panel panel-ntspl inner-panel">
                            <div class="panel-heading header-style">
                                <h3 class="panel-title">
                                    Order Number #@item.Order_No
                                    <span class="panel-options resbtn">
                                        <a href="/student/viewpackagedetail/@item.Package_ID">
                                            <button type="button" class="btn btn-blue btn-xs">View Package Details</button>
                                        </a>
                                    </span>
                                </h3>
                            </div>
                            <div class="panel-body test-panel-body pannel-padding">
                                <table class="table table-hover">
                                    <tbody>
                                        <tr>
                                            <th scope="row" class="td-width-one">Package Name</th>
                                            <td class="right-td td-width-two">@item.Package_Name</td>
                                        </tr>
                                        <tr>
                                            <th scope="row" class="td-width-one">Subjects</th>
                                            <td class="right-td td-width-two">@item.subjects</td>
                                        </tr>
                                        <tr>
                                            <td>Chapters</td>
                                            <td class="right-td">@item.Chapters</td>
                                        </tr>
                                        <tr>
                                            <td>Expire Date</td>
                                            <td class="right-td">@item.Expiry_Date</td>
                                        </tr>
                                        <tr>
                                            <td>Price</td>
                                            <td class="price-color small-bolt">INR @string.Format("{0:0.00}", item.Total) </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                </div>
                        i++;
                    }
                }
                else
                {
                    <div class="row">
                        <div class="col-md-12 questions-cont text-center">
                            <div class="ful-hi-wi">
                               <div class="no-content-notification">There are no ordered items.</div>
                                @*<img src="images/cartimg.png">*@
                                @{
                    DigiChamps.Models.DigiChampsEntities DbContext = new DigiChamps.Models.DigiChampsEntities();
                    var list = DbContext.tbl_DC_Sample_Image.Where(x => x.Image_Type == "Order" && x.Is_Active == true && x.Is_Deleted == false).FirstOrDefault();
                    ViewBag.list = list.Image_URL;
                            <img src="~/Images/SampleImage/@ViewBag.list" style="width:100%" class="img-responsive voffset3" />
                                }

                                <div class="foraddbtn">
                                    <a href="/student/packagepreview"><button type="button" class="btn btn-primary addbtn">BUY NOW</button></a>
                                </div>
                            </div>

                        </div>
                    </div>
                }

            </div>
        </div>
        <!-- Question Panel Ends -->
    </div>
</div>