DigiChamps/Controllers/MentorDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
//using System.Web.Http;
using System.Web.Mvc;
using DigiChamps.Models;


namespace DigiChamps.Controllers
{
    public class MentorDashboardController : Controller
    {
        DigiChampsEntities ob = new DigiChampsEntities();
        public ActionResult Index()
        {
           
            return RedirectToAction("Login");
           
        }
        
        public ActionResult Logout()
        {
            Session["MentorLogin"] = null;
            Session.Abandon();
           
            return RedirectToAction("Login");
        }
         [HttpGet]
        public ActionResult Login()
        {
            if (Session["MentorLogin"] != null)
            {

                return RedirectToAction("Dashboard");
               
                
            }
            else
            {
                return View();
            }
        }
        public ActionResult Login(string User_name, string password)
        {
            
                 var data = ob.tbl_DC_MentorDashboardLogin.Where(x => x.Username.Equals(User_name)
                        && x.Password.Equals(password)&&x.Is_Active==true&&x.Is_Delete==false).FirstOrDefault();
                    if(data!=null)
                    {
                        Session["MentorLogin"] = "Y";
                        return RedirectToAction("Dashboard");
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Invalid credential for admin login.";
                        return View();
                    }
                
        }
        public ActionResult Dashboard()
        {
            if (Session["MentorLogin"] == null)
                return RedirectToAction("Login"); 
            else
            return View();
        }
        public ActionResult ViewExamDetails()
        {
            
            if (Request.QueryString["ResId"]==null)
            {
                return View("Index");
            }
            else
            {
                Session["ResId"] = Request.QueryString["ResId"].ToString();
            }
            return View();
        }
        public ActionResult ViewStudentDetails()
        {

            if (Request.QueryString["RegdId"] == null)
            {
                return View("Index");
            }
            else
            {
                Session["RegdId"] = Request.QueryString["RegdId"].ToString();
            }
            return View();
        }
        public class ExamDetailsCls
        {


            public int? CountAppeared { get; set; }
            public int? CountAnswered { get; set; }
            public int? slno { get; set; }
          
            //public string AcademicResult { get; set; }
            //public string SocialResult { get; set; }
            public string studentname { get; set; }
            public string mobile { get; set; }
            public DateTime? examdate { get; set; }
            public int? totalquestions { get; set; }
            public int? Attemptedques { get; set; }
            public int? NotAttemptedques { get; set; }
            public int? Correctques { get; set; }
            public int? Result_ID { get; set; }
            public int? Regd_ID { get; set; }
        }
        public class ExamQuesAnsCls
        {
            public int Result_ID { get; set; }            
            public string Question { get; set; }
            public string First_Option { get; set; }
            public string Second_Option { get; set; }
            public string Third_Option { get; set; }
            public string Fourth_Option { get; set; }
            public string Answer { get; set; }
            public string Correct_Answer { get; set; }
        }
        public ActionResult GetAllExamDetails()
        {
            try
            {
                //var regs = ob.tbl_DC_Registration.ToList();
                //var exams = ob.tbl_DC_Psychometric_Exam_Result.ToList();
                List<ExamDetailsCls> res = (from a in ob.tbl_DC_Registration
                                            let b = ob.tbl_DC_Psychometric_Exam_Result
                                                .Where(
                                                     cl => cl.Regd_ID == a.Regd_ID
                                                    )
                                                .OrderBy(cl => cl.Result_ID) // Todo: Might need to be descending?
                                                .FirstOrDefault()
                                            where b != null
                                            orderby b.Regd_ID descending                           
                           select new ExamDetailsCls
                           {
                               studentname = a.Customer_Name,
                               mobile = a.Mobile,
                               examdate = a.Modified_Date,
                               totalquestions =b.Question_Nos,
                               Attemptedques =b.Question_Attempted,
                               NotAttemptedques = b.Question_Nos - b.Question_Attempted,
                               Correctques = b.Total_Correct_Ans,
                               Result_ID = b.Result_ID,
                               Regd_ID =b.Regd_ID,


                               //AcademicResult = ob.tbl_DC_Psychometric_Result_Pattern
                               //            .Where(x => x.Pattern_Code.Equals(b.AcademicId) && x.PsychometricType == 1).
                               //            Select(x => x.Comment).FirstOrDefault(),
                               //SocialResult = ob.tbl_DC_Psychometric_Result_Pattern
                               //.Where(x => x.Pattern_Code.Equals(b.InterpersonalId) && x.PsychometricType == 2).
                               //Select(x => x.Comment).FirstOrDefault(),
                               
                           }).ToList();
                int cnt = 1;
                foreach(var a in res.ToList())
                {
                    a.slno = cnt++;
                }
                var result = new
                {
                    draw = 1,
                    recordsTotal = res.ToList().Count(),
                    recordsFiltered = res.ToList().Count(),
                    data = res.ToList().ToArray()
                };

                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult GetDashboardCount()
        {
            try
            {
                //var regs = ob.tbl_DC_Registration.ToList();
                //var exams = ob.tbl_DC_Psychometric_Exam_Result.ToList();
                List<ExamDetailsCls> res = (from a in ob.tbl_DC_Registration
                                            let b = ob.tbl_DC_Psychometric_Exam_Result
                                                .Where(
                                                     cl => cl.Regd_ID == a.Regd_ID
                                                    )
                                                .OrderBy(cl => cl.Result_ID) // Todo: Might need to be descending?
                                                .FirstOrDefault()
                                            where b != null
                                            orderby b.Regd_ID descending
                                            select new ExamDetailsCls
                                            {
                                                studentname = a.Customer_Name,
                                                mobile = a.Mobile,
                                                examdate = a.Modified_Date,
                                                totalquestions = b.Question_Nos,
                                                Attemptedques = b.Question_Attempted,
                                                NotAttemptedques = b.Question_Nos - b.Question_Attempted,
                                                Correctques = b.Total_Correct_Ans,
                                                Result_ID = b.Result_ID,
                                                Regd_ID = b.Regd_ID,


                                                //AcademicResult = ob.tbl_DC_Psychometric_Result_Pattern
                                                //            .Where(x => x.Pattern_Code.Equals(b.AcademicId) && x.PsychometricType == 1).
                                                //            Select(x => x.Comment).FirstOrDefault(),
                                                //SocialResult = ob.tbl_DC_Psychometric_Result_Pattern
                                                //.Where(x => x.Pattern_Code.Equals(b.InterpersonalId) && x.PsychometricType == 2).
                                                //Select(x => x.Comment).FirstOrDefault(),

                                            }).ToList();
                List<ExamDetailsCls> resAnswered = (from a in ob.tbl_DC_Registration
                                            let b = ob.tbl_DC_Psychometric_Exam_Result
                                                .Where(
                                                     cl => cl.Regd_ID == a.Regd_ID&&cl.Total_Correct_Ans==20
                                                    )
                                                .OrderBy(cl => cl.Result_ID) // Todo: Might need to be descending?
                                                .FirstOrDefault()
                                            where b != null
                                            orderby b.Regd_ID descending
                                            select new ExamDetailsCls
                                            {

DigiChamps/Views/Shared/Getpackagemodule.cshtml
@{
    Layout = null;
}
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
       <div class="box box-blue">
                <div class="box-title">
                    <h3><i class="fa fa-file-text"></i>Module Names</h3>
                    <div class="box-tool">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
                    </div>
                </div>
                <div class="box-content">
                    <div class="table-responsive">
                        <table class="table table-advance" id="table2">
                            <thead>
                                <tr>
                                    <th>Sl No.</th>
                                    <th>Module Name</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    int i = 0;
                                }
                                @foreach (var b in ViewBag.Pacakge_Modules)
                                {
                                    <tr>
                                        <td>@(i += 1)</td>
                                        <td>@b.Module_Name</td>
                                        <td>@Html.ActionLink(" ", "Deletemodule_frmpackage", "Admin", new { id = @b.PackageDtl_ID, pkid = @b.Package_ID }, new { @class = "btn btn-sm btn-danger show-tooltip fa fa-trash-o", @onclick = "return confirm('Are you sure want to delete the package?')", @data_original_title = "Delete", @title = "Delete" })</td>
                                        @*<td>
                                            <a href="#" id="Dlt" onclick="return confirm('Are you sure want to delete the Module?')" class="btn btn-sm btn-danger show-tooltip fa fa-trash-o" title="Delete" />
                                        </td>*@
</tr>


                                }
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>



<script>
    $('#table2').dataTable({
        "aLengthMenu": [
            [10, 15, 25, 50, 100, -1],
            [10, 15, 25, 50, 100, "All"]
        ],
        "iDisplayLength": 10,
        "oLanguage": {
            "sLengthMenu": "_MENU_ Records per page",
            "sInfo": "_START_ - _END_ of _TOTAL_",
            "sInfoEmpty": "0 - 0 of 0",
            "oPaginate": {
                "sPrevious": "Prev",
                "sNext": "Next"
            }
        },
        "aoColumnDefs": [{
            'bSortable': false,
            'aTargets': [0]
        }]
    });
 
</script>


    


.

DigiChamps/Views/Shared/MentorDashboard.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.js"></script>
    <script>
        if (!window.moment) {
            document.write('<script src="assets/plugins/moment/moment.min.js"><\/script>');
        }
    </script>
</head>
<body >
    <div class="container-fluid  bg-white" >
        <nav class=" navbar navbar-white bg-white">
            <a class="navbar-brand" href="#">
                <img src="~/Images/Digichamps_logo.png" class="d-inline-block align-top" alt="">

            </a>
            <h3 class="text-dark">Mentorship Dashboard</h3>
            <a href="@Url.Action("Logout", "MentorDashboard" )"><i class="fa fa-off"></i>Logout</a>
        </nav>
        <div class="clearfix" style="margin-bottom:15px;"></div>
        <div style="margin-top:50px;">
            @RenderBody()
        </div>

        <!-- Footer -->
        <footer class="page-footer font-small blue pt-4 mt-4">

            <!-- Copyright -->
            <div class="footer-copyright text-center py-3">
                © 2018 Copyright:
                <a href="https://learn.odmps.org/">learn.odmps.org</a>
            </div>
            <!-- Copyright -->

        </footer>
    </div>

</body>
</html>

DigiChamps/Views/Shared/MentorshipDashboard.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.js"></script>
    <script>
        if (!window.moment) {
            document.write('<script src="assets/plugins/moment/moment.min.js"><\/script>');
        }
    </script>
</head>
<body >
    <div class="container-fluid  bg-white" >
        <nav class=" navbar navbar-white bg-white">
            <a class="navbar-brand" href="#">
                <img src="~/Images/Digichamps_logo.png" class="d-inline-block align-top" alt="">

            </a>
            <h3 class="text-dark">Mentorship Dashboard</h3>
            <a href="@Url.Action("Logout", "MentorDashboard" )"><i class="fa fa-off"></i>Logout</a>
        </nav>
        <div class="clearfix" style="margin-bottom:15px;"></div>
        <div style="margin-top:50px;">
            @RenderBody()
        </div>

        <!-- Footer -->
        <footer class="page-footer font-small blue pt-4 mt-4">

            <!-- Copyright -->
            <div class="footer-copyright text-center py-3">
                © 2018 Copyright:
                <a href="https://learn.odmps.org/">learn.odmps.org</a>
            </div>
            <!-- Copyright -->

        </footer>
    </div>

</body>
</html>

DigiChamps/Views/Shared/_MentorLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title> @ViewBag.Title | DIGICHAMPS</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/Student_assets/images/fav-icon.jpg" rel="shortcut icon" />
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/chosen-bootstrap/chosen.min.css">
    <link rel="stylesheet" href="~/assets/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/Education_freebie/stylesheet.css">
    <link href="~/assets/jquery-ui/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/assets/fullcalendar/fullcalendar/fullcalendar.css" rel="stylesheet" />
    <link href="~/assets/datepicker/css/datepicker.css" rel="stylesheet" />
    <link href="~/css/flaty-responsive.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/flaty.css">
    <link rel="shortcut icon" href="~/img/favicon.html">
    <link href="~/assets/data-tables/bootstrap3/dataTables.bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/assets/bootstrap-fileupload/bootstrap-fileupload.css" />
    <link href="~/css/croppie.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/manual.css">
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    @*<script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
            })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-93241591-1', 'auto');
            ga('send', 'pageview');
        </script>*@
</head>
<body>
    <div class="loader-ajax-container">
        <div class="cssload-container">
            <div class="cssload-loading"><i></i><i></i><i></i><i></i></div>
        </div>
    </div>
    <!-- BEGIN Theme Setting -->
    <!-- END Theme Setting -->
    <!-- BEGIN Navbar -->
    <div id="navbar" class="navbar">
        <button type="button" class="navbar-toggle navbar-btn collapsed" data-toggle="collapse" data-target="#sidebar">
            <span class="fa fa-bars"></span>
        </button>
        <a class="navbar-brand" href="#">
            <img src="~/Images/Digichamps_logo.png" />
        </a>
        <!-- BEGIN Navbar Buttons -->
        <ul class="nav flaty-nav pull-right">
            <li class="hidden-xs">
                <a data-toggle="dropdown" class="dropdown-toggle noti" href="#">
                    <i class="fa fa-bell"></i>
                    <span class="badge badge-important count"></span>
                </a>
                <!-- BEGIN Notifications Dropdown -->
                <ul class="dropdown-navbar dropdown-menu" id="notiContent">
                    @*
                        <li class="nav-header">
                            <i class="fa fa-warning"></i>
                            5 Notifications
                        </li>*@
                    @*
                        <li class="notify">
                            <a href="#">
                                <i class="fa fa-comment orange"></i>
                                <p>New Tickets</p>
                                <span class="badge badge-warning">4</span>
                            </a>
                        </li>*@
                </ul>
                <!-- END Notifications Dropdown -->
            </li>
            <li class="user-profile">
                <a data-toggle="dropdown" href="#" class="user-menu dropdown-toggle">
                    <img class="nav-user-photo" src="~/Images/images.png" alt="Penny's Photo" />
                    <span class="hhh" id="user_info">
                        @Html.Raw(Convert.ToString(Session["username"]).Trim().ToUpper())
                    </span>
                    <i class="fa fa-caret-down"></i>
                </a>
                <!-- BEGIN User Dropdown -->
                <ul class="dropdown-menu dropdown-navbar" id="user_menu">
                    <li class="nav-header">

                        Logined From @Session["Time"]
                    </li>
                    @*<li>
                            <a href="/Admin/ChangePassword">
                                <i class="fa fa-cog"></i>
                                Change Password
                            </a>
                        </li>*@
                    @*
                        <li>
                            <a href="/Admin/EditProfile">
                                <i class="fa fa-user"></i>
                                Edit Profile
                            </a>
                        </li>*@
                    <li class="divider visible-xs"></li>
                    <li class="visible-xs">
                        <a href="#">
                            <i class="fa fa-tasks"></i>
                            Tasks
                            <span class="badge badge-warning">4</span>
                        </a>
                    </li>
                    <li class="visible-xs">
                        <a href="#">
                            <i class="fa fa-bell"></i>
                            Notifications
                            <span class="badge badge-important">8</span>
                        </a>
                    </li>
                    <li class="visible-xs">
                        <a href="#">
                            <i class="fa fa-envelope"></i>
                            Messages
                            <span class="badge badge-success">5</span>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="@Url.Action("logout", "Admin" )"><i class="fa fa-off"></i>Logout</a>
                    </li>
                </ul>
                <!-- BEGIN User Dropdown -->
            </li>
            @*@*<li class="user-profile">
                    <a data-toggle="dropdown" href="#" class="user-menu dropdown-toggle">
                        <img class="nav-user-photo" src="~/Images/images.png" alt="Penny's Photo" />
                        <span class="hhh" id="user_info">

                        </span>
                        <i class="fa fa-caret-down"></i>
                    </a>
                    <!-- BEGIN User Dropdown -->
                    <ul class="dropdown-menu dropdown-navbar" id="user_menu">

                        <li class="divider"></li>
                        @*<li>
                            <a href="@Url.Action("AddSchoolAdmin", "Admin" )"><i class="fa fa-off"></i>Admin Profile</a>
                        </li>
                    </ul>
                    <!-- BEGIN User Dropdown -->
                </li>*@
            <!-- END Button User -->
        </ul>
        <!-- END Navbar Buttons -->
        @*@RenderBody()*@

    </div>
    <div>
        <!-- BEGIN Sidebar -->
        <div id="sidebar" class="navbar-collapse collapse">
            <!-- BEGIN Navlist -->

            <ul id=bs-navbar class="nav nav-list">
                <li>
                    <a href="@Url.Action("SchoolDashBoard", "School")">
                        <i class="fa fa-dashboard"></i>
                        <span>Dashboard</span>
                    </a>
                </li>   
                <li>
                    <a href="/MentorDetails/UploadDetails">
                    <i class="fa fa-dropbox"></i>
                        <span>Upload Details</span>
                    </a>
                </li>  
                <li>
                    <a href="/MentorDetails/StudentDetails">
                        <i class="fa fa-tasks"></i>
                        <span>Student Details</span>
                    </a>
                </li>  
                <li>
                    <a href="/MentorDetails/Firstcallsummary">
                        <i class="fa fa-tasks"></i>
                        <span>Summary</span>
                    </a>
                </li> 
                <li>
                    <a href="/MentorDetails/Allotmentor">
                        <i class="fa fa-tasks"></i>
                        <span>Alloting Mentor</span>
                    </a>
                </li>                          
            </ul>

            <div id="sidebar-collapse" class="visible-lg">
                <i class="fa fa-angle-double-left"></i>
            </div>
            <!-- END Sidebar Collapse Button -->
        </div>
        }
        <!-- END Sidebar -->
        <!-- BEGIN Content -->
        <div id="main-content">
            @if (TempData["SuccessMessage"] != null)
            {
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <div style="font-size: 13px; color:#5ead34;"><i class="fa fa-check-circle"></i> @TempData["SuccessMessage"]</div>
                </div>
            }
            @if (@TempData["ErrorMessage"] != null)
            {
                <div class="alert alert-danger" role="alert" id="errormsg">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <div style="font-size: 13px;"><i class="fa fa-times-circle"></i> @TempData["ErrorMessage"]</div>
                </div>
            }
            @if (@TempData["WarningMessage"] != null)
            {
                <div class="alert alert-warning" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <div style="font-size: 13px; color:#ffaf36;"><i class="fa fa-exclamation-circle"></i> @TempData["WarningMessage"]</div>
                </div>
            }


            @RenderBody()
            <!-- BEGIN Session check -->
            <!-- END Session check -->
            @*<footer>
                    <p>2016 © Designed by NTSPL.</p>
                </footer>*@
            <a id="btn-scrollup" class="btn btn-circle btn-lg" href="#"><i class="fa fa-chevron-up"></i></a>
        </div>
    </div>
    @* <script src="~/assets/jquery/jquery-2.1.1.min.js"></script>*@
    <script src="~/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/assets/jquery-cookie/jquery.cookie.js"></script>
    <script src="~/assets/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/assets/datepicker/js/bootstrap-datepicker.js"></script>
    <script src="~/assets/data-tables/jquery.dataTables.js"></script>
    <script src="~/assets/data-tables/bootstrap3/dataTables.bootstrap.js"></script>
    <!--Validation scripts-->
    <script type="text/javascript" src="~/assets/jquery-validation/dist/jquery.validate.min.js"></script>
    <script type="text/javascript" src="~/assets/jquery-validation/dist/additional-methods.min.js"></script>
    <script type="text/javascript" src="~/assets/chosen-bootstrap/chosen.jquery.min.js"></script>
    <!--flaty scripts-->
    <script src="~/js/flaty.js"></script>
    <script src="~/js/flaty-demo-codes.js"></script>
    @*<script src="~/Student_assets/assets/js/jquery.signalR-2.2.0.min.js"></script>*@
    @*<script type="text/javascript" src="~/signalr/hubs"></script>*@
    <script>
        
        $('.datepicker').datepicker().on('changeDate', function (e) {
            $(this).datepicker('hide');
        });
        $(document).ready(function () {
            $('#table1').dataTable();
            
            setTimeout(function () {
                setActive();
            }, 350);
        });
        function setActive() {

            aObj = document.getElementById('bs-navbar').getElementsByTagName('a');

            for (i = 0; i < aObj.length; i++) {
                // if (document.location.href.indexOf(aObj[i].href) >= 0) {
                if (document.location.href === aObj[i].href) {
                    if ($(aObj[i]).parent().parent().hasClass('nav')) {
                        $(aObj[i]).parent('ul li').addClass('active');

                    }
                    else {
                        $(aObj[i]).parent().parent().parent('li').addClass('active');
                        $(aObj[i]).addClass('active');
                    }
                }
            }
        }
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>