DigiChamps/Controllers/TeacherAccessController.cs
using CrystalDecisions.Shared.Json;
using DigiChamps.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Drawing.Imaging;
using ClosedXML.Excel;
using System.Data;
using System.Collections;
using System.Net;
using System.Text;
using System.Web.Script.Serialization;
using System.Collections.Specialized;
using System.Net.Mail;
using System.Configuration;
using System.Text.RegularExpressions;
using System.Threading;

namespace DigiChamps.Controllers
{
    public class TeacherAccessController : Controller
    {
        DigiChampsEntities DbContext = new DigiChampsEntities();
        DateTime today = DigiChampsModel.datetoserver();

        public ActionResult Index()
        {
            return RedirectToAction("Login");
        }
        #region ---------- Teacher rDashboard ------------
        public ActionResult TeacherDashboard()
        {
            var username = Convert.ToString(Session["Mobile"]);
            if (username != null && username != "")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }

        }
        #endregion

        #region ---------------- ---Login ------------------

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Login(string User_name, string password)
        {
            try
            {
                var obj = DbContext.Teachers.Where(x => x.Mobile == User_name && x.Password == password).FirstOrDefault();

                if (obj != null)
                {
                    Session["TeacherId"] = obj.TeacherId;
                    Session["SchoolId"] = obj.SchoolId;
                    Session["Name"] = obj.Name;
                    Session["Email"] = obj.Email;
                    Session["Mobile"] = obj.Mobile;
                    Session["DepartmentName"] = obj.DepartmentName;
                    Session["Photo"] = obj.Photo;
                    Session["IsHead"] = obj.IsHead;

                    return RedirectToAction("TeacherDashboard");
                }
                else
                {
                    TempData["ErrorMessage"] = "Invalid credential for Teacher login.";
                    return View();

                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Something went wrong.";
            }
            return View();
        }
        #endregion

        #region ------------ MyProfile-------------------
        [HttpGet]
        public ActionResult MyProfile()
        {
            var username = Convert.ToString(Session["Mobile"]);
            if (username != null && username != "")
            {
                var TeacherId = Convert.ToInt32(Session["TeacherId"]);
                Teacher _teachr = DbContext.Teachers.Where(x => x.TeacherId == TeacherId).FirstOrDefault();
                ViewBag.TeacherId = _teachr.TeacherId;
                ViewBag.Name = _teachr.Name;
                ViewBag.Email = _teachr.Email;
                //string date = Convert.ToString(_teachr.DateOfBirth).Substring(0, 10);
                //ViewBag.dateofbirth = date;
                ViewBag.Mobile = _teachr.Mobile;
                ViewBag.DepartmentName = _teachr.DepartmentName;
                ViewBag.IsHead = _teachr.IsHead;
                ViewBag.image = _teachr.Photo;

                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        [HttpPost]
        public ActionResult EditProfile(long TeacherId, HttpPostedFileBase Photo, string Name, string Mobile, string Email, string DepartmentName, string IsHead)
        {
            var username = Convert.ToString(Session["Mobile"]);
            if (username != null && username != "")
            {
                try
                {
                    var teacherid = Convert.ToInt32(Session["TeacherId"]);
                    var alldetail = DbContext.Teachers.Where(x => x.TeacherId == TeacherId).FirstOrDefault();
                    string image = string.Empty;
                    if (alldetail != null)
                    {
                        alldetail.Name = Name;
                        alldetail.ModifiedOn = today;
                        alldetail.Mobile = Mobile;
                        alldetail.Email = Email;
                        alldetail.DepartmentName = DepartmentName;
                        if (IsHead == "on")
                        {
                            alldetail.IsHead = true;
                        }
                        else
                        {
                            alldetail.IsHead = false;
                        }
                        string guid = Guid.NewGuid().ToString();
                        if (Photo != null)
                        {
                            var fileName = Path.GetFileName(Photo.FileName.Replace(Photo.FileName.Split('.').FirstOrDefault().ToString(), guid.ToString()));
                            image = Convert.ToString(fileName);
                            var path = Path.Combine(Server.MapPath("~/Images/TeacherAccess/"), fileName);
                            Photo.SaveAs(path);
                            alldetail.Photo = image;
                        }

                        DbContext.Entry(alldetail).State = EntityState.Modified;
                        DbContext.SaveChanges();
                        TempData["SuccessMessage"] = " Successfully Edit Profile ";
                        return RedirectToAction("MyProfile");
                    }
                }
                catch
                {
                    return View();
                }
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }


        [HttpGet]
        public ActionResult ChangePassword()
        {
            var username = Convert.ToString(Session["Mobile"]);
            if (username != null && username != "")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
        [HttpPost]
        public ActionResult TeacherChangePassword(string Old_Password, string New_Password, string Conf_Password)
        {
            string message = string.Empty;
            var username = Convert.ToString(Session["Mobile"]);
            if (username != null && username != "")
            {
                if (New_Password != "" && Conf_Password != "" && Old_Password != "")
                {
                    var data = DbContext.Teachers.Where(x => x.Password == Old_Password).FirstOrDefault();

                    if (data != null)
                    {
                        if (New_Password == Conf_Password)
                        {
                            data.Password = New_Password;
                            DbContext.Entry(data).State = EntityState.Modified;
                            DbContext.SaveChanges();
                            TempData["SuccessMessage"] = " Successfully Edit Profile ";
                            return RedirectToAction("ChangePassword");
                        }
                        else
                        {
                            TempData["ErrorMessage"] = " New Password And Confirm Password Did Not Match, ";
                            return RedirectToAction("ChangePassword");
                        }
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Please Enter Old Password, Did Not Match, ";
                        return RedirectToAction("ChangePassword");
                    }


                }
                else
                {
                    TempData["WarningMessage"] = "Please Enter Password. ";
                    return RedirectToAction("ChangePassword");
                }
            }
            else
            {
                return RedirectToAction("Login");
            }

        }


        #endregion

        #region  -----------------Logout ---------------------

        public ActionResult Logout()
        {
            Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
        #endregion

        #region -----------------Assigned Subject------------------
        public ActionResult AssignedSubject()
        {
            var username = Convert.ToString(Session["Mobile"]);
            if (username != null && username != "")
            {

                var teacherid = Convert.ToInt32(Session["TeacherId"]);
                var Schoollist = DbContext.tbl_DC_School_Info.Where(a => a.IsActive == true).ToList();
                var boardlist = DbContext.tbl_DC_Board.Where(a => a.Is_Active == true && a.Is_Deleted == false).ToList();
                var classlist = DbContext.tbl_DC_Class.Where(a => a.Is_Active == true && a.Is_Deleted == false).ToList();
                var sectionlist = DbContext.tbl_DC_Class_Section.Where(a => a.IsActive == true).ToList();
                var subjectlist = DbContext.tbl_DC_Subject.Where(a => a.Is_Active == true && a.Is_Deleted == false).ToList();
                var teacherslist = DbContext.Teachers.Where(a => a.Active == 1).ToList();
                var assignteacherlist = DbContext.tbl_DC_AssignSubjectToTeacher.Where(a => a.Is_Active == true && a.Teacher_ID == teacherid).ToList();
                var res = (from a in assignteacherlist
                           join b in teacherslist on a.Teacher_ID equals b.TeacherId

DigiChamps/Views/TeacherAccess/AssignedSubject.cshtml
@{
    ViewBag.Title = "AssignedSubject";
    Layout = "~/Views/Shared/_TeacherAccessLayout.cshtml";
}
@model IEnumerable<DigiChamps.Models.AssignTeacherCls>

<div id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="~/TeacherAccess/TeacherDashboard">Home</a>
            <span class="divider"><i class="fa fa-angle-right"></i></span>
        </li>      
          <li class="active">Assigned Subject</li>        
    </ul>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-title">
                <h3><i class="fa fa-file"></i> Subjects Assigned To Me </h3>
                @*<div class="box-tool box-tooll">
                        <a class="btn btn-primary" href="/School/UploadAssignSubjectToTeacher"><i class="fa fa-upload"></i><span> Upload Excel</span></a>

                        <a class="btn btn-primary" href="/School/CreateAssignSubjectToTeacher"><i class="fa fa-plus"></i><span> Assign Subject</span></a>
                    </div>*@
            </div>
            <div class="box-content">

                <div class="table-responsive">
                    <table class="table table-advance" id="table1">

                        <thead>
                            <tr>
                                <th>Sl No.</th>
                                <th>School</th>
                                <th>Board</th>
                                <th>Class</th>
                                <th>Section</th>
                                <th>Subject</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                int rowNo = 0;
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@(rowNo += 1)</td>
                                        <td>@item.SchoolName</td>
                                        <td>@item.BoardName</td>
                                        <td>@item.ClassName</td>
                                        <td>@item.SectionName</td>
                                        <td>@item.SubjectName</td>
                                        <td>
                                            @Html.ActionLink("View Student", "StudentDetails", "TeacherAccess", new { SectionId = @item.SectionId }, new { @class = "btn btn-sm btn-primary show-tooltip", @data_original_title = "View Student", @title = "View Student Details" })
                                        </td>
                                    </tr>
                                }
                            }


                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div>

DigiChamps/Views/TeacherAccess/CreateExam.cshtml
@{
    ViewBag.Title = "CreateExam";
    Layout = "~/Views/Shared/_TeacherAccessLayout.cshtml";
}

<div id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="~/Admin/AdminDashboard">Home</a>
            <span class="divider"><i class="fa fa-angle-right"></i></span>
            <a href="~/SchoolReport/ExamList">Exam Category List</a>
            <span class="divider"><i class="fa fa-angle-right"></i></span>
            <span>Create</span>
        </li>
        @if (ViewBag.Breadcrumb != null)
        {
            <li class="active">@ViewBag.Breadcrumb</li>
        }
    </ul>
</div>

<div class="page-content-wrap">

    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("SaveExam", "TeacherAccess", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data", id = "validation-form" }))
            {
                @Html.AntiForgeryToken();
                <div class="box">
                    <div class="box-title">
                        <h3><i class="fa fa-file"></i>Create Exam Category</h3>
                    </div>

                    <div class="box-content">
                        <div class="form-group" style="margin-top:30px">
                            <input type="hidden" id="id" name="id" value="@ViewBag.id" />
                            <label for="textfield5" class="col-sm-3 col-lg-2 control-label">NegativeMarks</label>
                            <div class="col-sm-9 col-lg-7 controls">
                                <input type="text" name="name" class="form-control" id="name" value="@ViewBag.name" />
                            </div>
                        </div>
                        <br /><br />
                        <div class="form-group last box-tooll">
                            <div class="col-sm-9 col-sm-offset-3 col-lg-7 col-lg-offset-2">
                                <a href="@Url.Action("ExamList", "SchoolReport")" class="btn btn-primary"><i class="fa fa-undo"></i><span>  Back</span>  </a>
                                <button id="btnSearch" type="submit" class="btn btn-primary btn-success"><i class="fa fa-check green-i"></i><span>Submit</span> </button>

                            </div>
                        </div>
                    </div>

                </div>


            }
        </div>

    </div>


</div>

DigiChamps/Views/TeacherAccess/GetAllEReportDetails.cshtml
@{
    ViewBag.Title = "GetAllEReportDetails";
    Layout = "~/Views/Shared/_TeacherAccessLayout.cshtml";
}

@model IList<DigiChamps.Controllers.TeacherAccessController.Schoolwise_User_Class>

    <div class="form-horizontal" id="validation-form">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-title">
                        <h3><i class="fa fa-file"></i> E-Report Card List </h3>
                        <div class="box-tool box-tooll">
                            @*  <a class="btn btn-primary" href="/School/ExamType/"><i class="fa fa-plus"></i><span> Excel</span></a>*@
                        </div>
                    </div>
                    <div class="box-content">
                        @using (Html.BeginForm("GetAllEReportDetails", "TeacherAccess", FormMethod.Get,
                        new { @class = "form-horizontal", data_ajax = "false", enctype = "multipart/form-data", id = "validation" }))
                        {

                        <div class="clearfix"></div>
                        <div class="form-group">
                            <div class="col-md-3"></div>
                            <div class="col-md-2">School</div>
                            <div class="col-md-4">
                                <select id="ddlSchool" name="school" class="form-control">
                                    <option value="" selected="@(ViewBag.s==null?true:false)">All</option>
                                    @foreach (var a in ViewBag.schoolist)
                                    {
                                    <option value="@a.SchoolId" selected="@(ViewBag.s==a.SchoolId?true:false)">@a.SchoolName</option>
                                    }
                                </select>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group">
                            <div class="col-md-3"></div>
                            <div class="col-md-2">Board</div>
                            <div class="col-md-4">
                                <select id="ddlboard" name="board" class="form-control">
                                    @*
                                    <option value=" ">Select Board</option>
                                    @foreach (var a in ViewBag.Board)
                                    {
                                    <option value="@a.Board_Id">@a.Board_Name</option>
                                    }*@
                                </select>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group">
                            <div class="col-md-3"></div>
                            <div class="col-md-2">Class</div>
                            <div class="col-md-4">
                                <select id="ddlclass" name="cls" class="form-control"></select>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group">
                            <div class="col-md-3"></div>
                            <div class="col-md-2">Section</div>
                            <div class="col-md-4">
                                <select id="ddlsection" name="sec" class="form-control"></select>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group text-center">
                            <button id="btnsearch" class="btn btn-primary">Search</button>
                        </div>
                        <div class="clearfix"></div>
                        }
                    </div>
                    <div class="box-content">
                        <div class="table-responsive">
                            <table class="table table-advance" id="table1" width="100%">
                                <thead>
                                    <tr>
                                        <th>Sl No.</th>
                                        <th>Board</th>
                                        <th>School</th>
                                        <th>Class</th>
                                        <th>Section</th>
                                        <th>Regd No</th>
                                        <th>Student</th>
                                        <th>Email</th>
                                        <th>Phone</th>
                                        <th>Doc Name</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                    int i = 0;
                                    foreach (var a in Model)
                                    {
                                    <tr>
                                        <td> @(i=i + 1)</td>
                                        <td>@a.boardname</td>
                                        <td style="white-space:nowrap;max-width:100px;overflow:hidden; text-overflow:ellipsis;" title="@a.schoolname">@a.schoolname</td>
                                        <td style="white-space:nowrap;max-width:100px;overflow:hidden; text-overflow:ellipsis;" title="@a.Class_Name">@a.Class_Name</td>
                                        <td>@a.SectionName</td>
                                        <td>@a.Regd_ID</td>
                                        <td style="white-space:nowrap;max-width:100px;overflow:hidden; text-overflow:ellipsis;" title="@a.Customer_Name">@a.Customer_Name</td>
                                        <td style="white-space:nowrap;max-width:150px;overflow:hidden; text-overflow:ellipsis;" title="@a.Email">@a.Email</td>
                                        <td>@a.Mobile</td>
                                        <td>E-Report card</td>
                                        <td>Uploaded</td>
                                        <td>
                                            <a href="@a.EReportPath" target="_blank" title="View PDF" class="btn btn-success"><span>PDF</span></a>

                                        </td>
                                    </tr>
                                    }
                                    }
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/Student_assets/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Student_assets/Scripts/jquery.validate.min.js"></script>
    <script>

        $(document).ready(function () {

            GetBoard();
            GetClass('0');
            GetSection('0', '0');
            //   GetAllusers();
            $('#ddlboard').change(function () {
                GetClass($('#ddlboard').val());
            })
            $('#ddlclass').change(function () {
                GetSection($('#ddlclass').val(), $('#ddlSchool').val());
            })

            //========================GET BOARD DETAILS==================================//

            function GetBoard() {
                $('.loader-ajax-container').fadeIn(300);

                $.get("/SchoolReport/GetBoardList", function (data) {
                    debugger;
                    if (data.length > 0) {
                        $('#ddlboard').empty();
                        $('#ddlboard').append('<option selected>All</option>');

                        for (var i = 0; i < data.length; i++) {
                            $('#ddlboard').append('<option value="' + data[i].Board_Id + '">' + data[i].Board_Name + '</option>');
                        }
                        $('#ddlboard').val('@ViewBag.b');
                    }
                    else {
                        $('#ddlboard').empty();
                        $('#ddlboard').append('<option selected>All</option>');

                    }
                    $('.loader-ajax-container').fadeOut(300);
                }).fail(function (xhr) {
                    alert(xhr.responseText); // or whatever
                });
            }


            //========================GET BOARD DETAILS==================================//

            //========================GET CLASS DETAILS==================================//

            function GetClass(id) {
                $('.loader-ajax-container').fadeIn(300);
                if (id != '0') {

                    $.get("/SchoolReport/GetClassListdtl?id=" + id + "", function (data) {
                        debugger;
                        if (data.length > 0) {
                            $('#ddlclass').empty();

                            $('#ddlclass').append('<option selected>All</option>');

                            for (var i = 0; i < data.length; i++) {
                                $('#ddlclass').append('<option value="' + data[i].Class_Id + '">' + data[i].Class_Name + '</option>');

                            }
                            $('#ddlclass').val('@ViewBag.c');
                        }
                        else {
                            $('#ddlclass').empty();
                            $('#ddlclass').append('<option>All</option>');

                        }
                        $('.loader-ajax-container').fadeOut(300);
                    }).fail(function (xhr) {
                        alert(xhr.responseText); // or whatever
                    });
                }
                else {
                    $('#ddlclass').empty();
                    $('#ddlclass').append('<option selected>All</option>');
                    $('.loader-ajax-container').fadeOut(300);
                }
            }

            //========================GET CLASS DETAILS==================================//
            //========================GET SECTION DETAILS==================================//

            function GetSection(id, school) {
                $('.loader-ajax-container').fadeIn(300);
                if (id != '0') {

                    $.get("/SchoolReport/GetSectionListdtl?id=" + id + "&school=" + school, function (data) {
                        debugger;
                        if (data.length > 0) {
                            $('#ddlsection').empty();
                            $('#ddlsection').append('<option selected>All</option>');
                            for (var i = 0; i < data.length; i++) {
                                $('#ddlsection').append('<option value="' + data[i].SectionId + '">' + data[i].SectionName + '</option>')
                            }
                            $('#ddlsection').val('@ViewBag.se');
                        }
                        else {
                            $('#ddlsection').empty();
                            $('#ddlsection').append('<option>All</option>');
                        }
                        $('.loader-ajax-container').fadeOut(300);
                    }).fail(function (xhr) {
                        alert(xhr.responseText); // or whatever
                    });
                }
                else {
                    $('#ddlsection').empty();
                    $('#ddlsection').append('<option selected>All</option>');
                    $('.loader-ajax-container').fadeOut(300);
                }
            }

            //========================GET SECTION DETAILS==================================//


        })
    </script>