DigiChamps/Models/AcademicSession.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicSession
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> InsertedId { get; set; }
        public Nullable<long> ModifiedId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    }
}

DigiChamps/Controllers/MasterController.cs
using DigiChamps.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DigiChamps.Controllers
{
    public class MasterController : Controller
    {
        DigiChampsEntities dbContext = new DigiChampsEntities();

        public ActionResult Index()
        {
            return View();
        }

       
        public class AcademicSessionModel
        {
            public AcademicSession Asession { get; set; }
            public long ID { get; set; }
            public DateTime? Fromdate { get; set; }
            public DateTime? Todate { get; set; }

        }
        public class StudentDetailsModel
        {
       
            public int? ClassId { get; set; }
            public long StudentId { get; set; }
            public long SessionId { get; set; }
            public Guid? SectionId { get; set; }
            public int Regd_ID { get; set; }
            public string StudentName { get; set; }
            public string SessionName { get; set; }
            public string SectionName { get; set; }
            public string ClassName { get; set; }
            public bool IsCurrentSession { get; set; }


        }
        #region-------------------Academic  Session------------------------------
        public ActionResult AcademicSession()
        {
            var result = dbContext.AcademicSessions.ToList();
            return View(result);
        }

        public ActionResult CreateAcademicSession()
        {           
            return View();
        }
        [HttpPost]
        public ActionResult SaveAcademicSession( string Active, string name,DateTime? fdate,DateTime? tdate)
        {
            var result = dbContext.AcademicSessions.Where(a => a.Active == true).ToList();
                     
            if (Active == "on")
            {
                for (int i = 0; i < result.ToList().Count(); i++)
                {
                    AcademicSession asm = result.ToList()[i];
                    asm.ModifiedDate = DateTime.Now;
                    asm.Active = false;
                    dbContext.SaveChanges();
                }
            }
                AcademicSession session = new AcademicSession();
                session.InsertedDate = DateTime.Now;
                session.InsertedId = 1;
                session.ModifiedDate = DateTime.Now;
                session.ModifiedId = 1;
                session.Active = true;
                session.Status = "Created";
                session.Name = name;
                session.FromDate = fdate;
                session.ToDate = tdate;
                dbContext.AcademicSessions.Add(session);
                dbContext.SaveChanges();                 

            return RedirectToAction(nameof(AcademicSession));
        }
        public ActionResult EditAcademicSession(long id)
        {
            if (id > 0)
            {
                var session = dbContext.AcademicSessions.Where(a => a.ID == id).FirstOrDefault();
                ViewBag.ID = id;
                ViewBag.Name = session.Name;
                ViewBag.Fromdate = session.FromDate;
                ViewBag.Todate = session.ToDate;
                ViewBag.active = session.Active;
                return View();
            }
            else
            {
                return RedirectToAction(nameof(AcademicSession));
            }
        }
        [HttpPost]
        public ActionResult UpdateAcademicSession(string Active, long id,string name, DateTime? fdate, DateTime? tdate)
        {
            if (Active == "on")
            {
                var res = dbContext.AcademicSessions.Where(a => a.ID != id);
                if (res != null)
                {
                    for (int i = 0; i < res.ToList().Count(); i++)
                    {
                        AcademicSession asm = res.ToList()[i];                      
                        asm.ModifiedDate = DateTime.Now;
                        asm.Active = false;
                        dbContext.SaveChanges();
                    }
                }

            }
            var session = dbContext.AcademicSessions.Where(a =>a.ID == id).FirstOrDefault();
            session.Name = name;
            session.FromDate = fdate;
            session.ToDate = tdate;
            session.Active = true;
            session.ModifiedDate = DateTime.Now;
            session.Status = "Updated";
            dbContext.SaveChanges();
            return RedirectToAction(nameof(AcademicSession));
        }

        public ActionResult DeleteAcademicSession(long id)
        {
            var session = dbContext.AcademicSessions.Where(a => a.Active == true && a.ID == id).FirstOrDefault();
            session.Active = false;
            session.Status = "Deleted";
            dbContext.SaveChanges();
            return RedirectToAction(nameof(AcademicSession));
        }
        #endregion
        #region-------------- Session Student----------------------------

       
        public ActionResult StudentSession()
        {
            var student = dbContext.tbl_DC_Registration.Where(a => a.Is_Active == true && a.Is_Deleted == false).ToList();
            var studentdtl = dbContext.tbl_DC_Registration_Dtl.Where(a => a.Is_Active == true && a.Is_Deleted == false );
            var classs = dbContext.tbl_DC_Class.Where(a => a.Is_Active == true).ToList();
            var sections = dbContext.tbl_DC_Class_Section.Where(a => a.IsActive == true).ToList();
            var session = dbContext.AcademicSessions.Where(a => a.Active == true).ToList();
            var Academicsession = dbContext.AcademicSessions.Where(a => a.Active == true).ToList().FirstOrDefault();
            var result = dbContext.StudentSessions.Where(a => a.Active == true).ToList();
            var res = (from a in student
                       join b in studentdtl on a.Regd_ID equals b.Regd_ID
                       select new StudentDetailsModel
                       {
                           ClassId=b.Class_ID.Value,
                           SectionId=a.SectionId.Value,
                           Regd_ID=a.Regd_ID
                       }
                       ).ToList();

            for (var i = 0; i < res.ToList().Count; i++)
            {
                var details = result.Where(z => z.StudentId == res[i].Regd_ID && z.ClassId == res[i].ClassId && z.SessionId == Convert.ToInt64(Academicsession.ID)).FirstOrDefault();
                if (details==null)
                {
                 
                        StudentSession stusession = new StudentSession();
                        stusession.SessionId = Convert.ToInt64(Academicsession.ID);
                        stusession.StudentId = res[i].Regd_ID;
                        stusession.SectionId = res[i].SectionId;
                        stusession.ClassId = res[i].ClassId;
                        stusession.IsCurrentSession = true;
                        stusession.InsertedDate = DateTime.Now;
                        stusession.InsertedId = 1;
                        stusession.ModifiedDate = DateTime.Now;
                        stusession.ModifiedId = 1;
                        stusession.Active = true;
                        stusession.Status = "Created";
                        dbContext.StudentSessions.Add(stusession);
                        dbContext.SaveChanges();
                    
                }              
            }

            var studentsession = (from a in result
                                  join b in student on a.StudentId equals b.Regd_ID
                                  join c in studentdtl on b.Regd_ID equals c.Regd_ID
                                  select new StudentDetailsModel
                       {
                           ClassId = c.Class_ID.Value,
                           SectionId = a.SectionId.Value,
                           Regd_ID = a.StudentId.Value,
                           StudentName=b.Customer_Name,
                        ClassName = c.Class_ID == null ? "" : classs.Where(d => d.Class_Id == c.Class_ID).FirstOrDefault().Class_Name,
                        SectionName = ((b.SectionId == null && b.SectionId == Guid.Empty) ? "" : sections.Where(x => x.SectionId == b.SectionId).FirstOrDefault().SectionName),
                        SessionName= a.SectionId == null ? "" : session.Where(x => x.ID == a.SessionId).FirstOrDefault().Name
                       }
                     ).ToList();

            return View(studentsession);
        }
        #endregion

    }
}

DigiChamps/Views/Master/AcademicSession.cshtml
@{
    ViewBag.Title = "AcademicSession";
    Layout = "~/Views/Shared/_SchoolReportLayout.cshtml";
}


@model IEnumerable<DigiChamps.Models.AcademicSession>

<div id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="~/SchoolReport/Dashboard">Home</a>
            <span class="divider"><i class="fa fa-angle-right"></i></span>
        </li>
        <li>

            <span class="divider">AcademicSession</span>
        </li>

    </ul>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-title">
                <h3><i class="fa fa-file"></i> Session Student List </h3>
                <div class="box-tool box-tooll">
                    <a class="btn btn-primary" href="/Master/CreateAcademicSession"><i class="fa fa-plus"></i><span> Add Academic Session</span></a>
                </div>
            </div>

            <div class="box-content">
                <div class="table-responsive">
                    <table class="table table-advance" id="table1">

                        <thead>
                            <tr>
                                <th>S No.</th>
                                <th>Name</th>
                                <th>FromDate</th>
                                <th>ToDate</th>
                                <th>Status</th>
                                <th>ModifiedOn</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                int rowNo = 0;
                                foreach (var a in Model)
                                {
                            <tr>
                                <td>@(rowNo += 1)</td>
                                <td>@a.Name</td>
                                <td>@a.FromDate.Value.ToString("dd-MMM-yyyy")</td>
                                <td>@a.ToDate.Value.ToString("dd-MMM-yyyy")</td>
                                <td>@a.Active</td>
                                <td>@a.ModifiedDate.Value.ToString("dd-MMM-yyyy")</td>
                                <td>
                                    @Html.ActionLink(" ", "EditAcademicSession", "Master", new { id = a.ID }, new { @class = "btn btn-sm btn-primary fa fa-pencil", @title = "Edit" })
                                    <a href="@Url.Action("DeleteAcademicSession", "Master" , new { id = a.ID })" class="btn btn-sm btn-primary fa fa-trash" title="Remove" onclick="return confirm('Are You Sure Want To Remove This...?')"></a>

                                </td>
                            </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div>

DigiChamps/Views/Master/CreateAcademicSession.cshtml
@{
    ViewBag.Title = "CreateOrEditAcademicSession";
    Layout = "~/Views/Shared/_SchoolReportLayout.cshtml";
}

@model DigiChamps.Controllers.MasterController.AcademicSessionModel

<div id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="~/SchoolReport/Dashboard">Home</a>
            <span class="divider"><i class="fa fa-angle-right"></i></span>
        </li>
        <li>
            <a href="~/Master/AcademicSession">AcademicSession</a>
            <span class="divider"><i class="fa fa-angle-right"></i></span>
        </li>
        <li>
            <span>Create</span>
        </li>
    </ul>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-title">
                <h3><i class="fa fa-file"></i> Add AcademicSession</h3>
                <div class="box-tool box-tooll">
                </div>
            </div>            
            <div class="box-content">
                <div class="row">
                    @using (Html.BeginForm("SaveAcademicSession", "Master", FormMethod.Post, new { @class = "form-horizontal", data_ajax = "false", enctype = "multipart/form-data", id = "validation-form" }))
                    {
                        <div class="form-group">
                            <div class="col-md-3">

                            </div>
                            <div class="col-md-6">
                                <div class="col-sm-4 col-lg-4 controls">
                                    <label>Name*</label>
                                </div>
                                <div class="col-sm-8 col-lg-8 controls">
                                    <input type="text" id="name" name="name" class="form-control" required data-msg-required="Please select Name" placeholder="name" />
                                </div>

                                <div class="clearfix" style="margin-bottom:10px;"></div>
                            </div>
                            <div class="col-md-3">

                            </div>

                        </div>
                        <div class="form-group">
                            <div class="col-md-3">

                            </div>
                            <div class="col-md-6">
                                <div class="col-sm-4 col-lg-4 controls">
                                    <label>FromDate*</label>
                                </div>
                                <div class="col-sm-8 col-lg-8 controls">
                                    <input type="date" id="fdate" name="fdate" class="form-control" required data-msg-required="Please select fromdate" />
                                </div>

                                <div class="clearfix" style="margin-bottom:10px;"></div>
                            </div>
                            <div class="col-md-3">

                            </div>

                        </div>
                        <div class="form-group">
                            <div class="col-md-3">

                            </div>
                            <div class="col-md-6">
                                <div class="col-sm-4 col-lg-4 controls">
                                    <label>ToDate*</label>
                                </div>
                                <div class="col-sm-8 col-lg-8 controls">
                                    <input type="date" id="tdate" name="tdate" class="form-control" required data-msg-required="Please select Todate" />
                                </div>

                                <div class="clearfix" style="margin-bottom:10px;"></div>
                            </div>
                            <div class="col-md-3">

                            </div>

                        </div>
                        <div class="form-group">
                            <div class="col-md-3">

                            </div>
                            <div class="col-md-6">
                                <div class="col-sm-4 col-lg-4 controls">
                                    <label></label>
                                </div>
                                <div class="col-sm-2 col-lg-2 controls">
                                    <input type="checkbox" name="Active" class="form-control" />
                                </div>
                                <div class="col-sm-4 col-lg-4 controls">
                                    <label>Make As Current Session </label>
                                </div>

                                <div class="clearfix" style="margin-bottom:10px;"></div>
                            </div>
                            <div class="col-md-3">

                            </div>

                        </div>
                        <div class="form-group text-center">
                            <button type="submit" id="Reply" class="btn btn-large btn-primary btn-success"><i class="fa fa-check green-i"></i> <span>Submit</span></button>
                        </div>
                    }
                </div>

            </div>
        </div>
    </div>
</div>

DigiChamps/Views/Master/EditAcademicSession.cshtml
@{
    ViewBag.Title = "CreateOrEditAcademicSession";
    Layout = "~/Views/Shared/_SchoolReportLayout.cshtml";
}
 
<div id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="~/SchoolReport/Dashboard">Home</a>
            <span class="divider"><i class="fa fa-angle-right"></i></span>
        </li>
        <li>
            <a href="~/Master/AcademicSession">AcademicSession</a>
            <span class="divider"><i class="fa fa-angle-right"></i></span>
        </li>
        <li>
            <span>Create</span>
        </li>
    </ul>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-title">
                <h3><i class="fa fa-file"></i> Add AcademicSession</h3>
                <div class="box-tool box-tooll">
                </div>
            </div>
            <div class="box-content">
                <div class="row">
                    @using (Html.BeginForm("UpdateAcademicSession", "Master", FormMethod.Post, new { @class = "form-horizontal", data_ajax = "false", enctype = "multipart/form-data", id = "validation-form" }))
                    {
                        <div class="form-group">
                            <div class="col-md-3">

                            </div>
                            <div class="col-md-6">
                                <div class="col-sm-4 col-lg-4 controls">
                                    <label>Name*</label>
                                </div>
                                <div class="col-sm-8 col-lg-8 controls">
                                    <input type="hidden" name="id" class="form-control" value="@ViewBag.ID" />
                                    <input type="text" id="name" name="name" class="form-control" required data-msg-required="Please select Name" placeholder="name" value="@ViewBag.Name" />
                                </div>

                                <div class="clearfix" style="margin-bottom:10px;"></div>
                            </div>
                            <div class="col-md-3">

                            </div>

                        </div>
                        <div class="form-group">
                            <div class="col-md-3">

                            </div>
                            <div class="col-md-6">
                                <div class="col-sm-4 col-lg-4 controls">
                                    <label>FromDate*</label>
                                </div>
                                <div class="col-sm-8 col-lg-8 controls">
                                    <input type="date" id="fdate" name="fdate" class="form-control" required data-msg-required="Please select fromdate" value="@ViewBag.FromDate.ToString("yyyy-MM-dd")" />
                                </div>

                                <div class="clearfix" style="margin-bottom:10px;"></div>
                            </div>
                            <div class="col-md-3">

                            </div>

                        </div>
                        <div class="form-group">
                            <div class="col-md-3">

                            </div>
                            <div class="col-md-6">
                                <div class="col-sm-4 col-lg-4 controls">
                                    <label>ToDate*</label>
                                </div>
                                <div class="col-sm-8 col-lg-8 controls">
                                    <input type="date" id="tdate" name="tdate" class="form-control" required data-msg-required="Please select Todate" value="@ViewBag.ToDate.ToString("yyyy-MM-dd")" />
                                </div>

                                <div class="clearfix" style="margin-bottom:10px;"></div>
                            </div>
                            <div class="col-md-3">

                            </div>

                        </div>

                        <div class="form-group">
                            <div class="col-md-3">
                            </div>
                            <div class="col-md-6">
                                <div class="col-sm-4 col-lg-4 controls">
                                    <label></label>
                                </div>
                                <div class="col-sm-2 col-lg-2 controls">
                                    @if (ViewBag.active == true)
                                    {

                                        <input type="checkbox" checked name="Active" class="form-control" />
                                    }
                                    else
                                    {
                                        <input type="checkbox" name="Active" class="form-control" />
                                    }
                                </div>
                                <div class="col-sm-4 col-lg-4 controls">
                                    <label>Make As Current Session </label>
                                </div>
                                <div class="clearfix" style="margin-bottom:10px;"></div>
                            </div>
                            <div class="col-md-3">
                            </div>

                        </div>
                        <div class="form-group text-center">
                            <button type="submit" id="Reply" class="btn btn-large btn-primary btn-success"><i class="fa fa-check green-i"></i> <span>Submit</span></button>
                        </div>
                    }
                </div>

            </div>
        </div>
    </div>
</div>